import MainHeader from '@/components/main-header';
import './globals.css';

export const metadata = {
  title: 'Sebastian Prado',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
      <MainHeader/>
      {children}
      </body>
    </html>
  )
}
